config/routes.rb
Rails.application.routes.draw do

  root to: 'students#index'

  resources :students, only: [:index, :show]
  resources :marks, only: [:index]
  resources :absences, only: [:index]
  resources :disciplinary_sanctions, only: [:index]

end

app/models/api.rb
class Api

  def self.call uri
    response = Faraday.get (Settings.api.url + uri), content_type: 'application/json'
    JSON.parse response.body
  end
end

app/models/mark.rb
class Mark
	
end

app/models/student.rb
class Student

  def to_s
    "#{name} #{lastname}"
  end
end

app/controllers/absences_controller.rb
class AbsencesController < ApplicationController
  before_action :set_student
  before_action :set_person

  def index
    res = Api::call "/students/#{@student.id}/school_years"

    if params[:school_year].nil?
      @school_year = res['school_years'].last
      @school_year = @school_year['year'].to_s
    else
      @school_year = params[:school_year]
    end

    res_absences = Api::call "/students/#{@student.id}/absences/#{@school_year}"

    @school_years = res['school_years']
    @absences = res_absences['absences_for_year']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_student
    # For development. Remove this method when implementing authentication
    res = Api::call "/students/904"
    @student = OpenStruct.new res['student']
  end

  def set_person
    @person = OpenStruct.new @student['person']
  end
end

app/controllers/disciplinary_sanctions_controller.rb
class DisciplinarySanctionsController < ApplicationController
  before_action :set_student
  before_action :set_person

  # GET /disciplinary_sanctions
  def index
    res = Api::call "/students/#{@student.id}/school_years"

    if params[:school_year].nil?
      @school_year = res['school_years'].last
      @school_year = @school_year['year'].to_s
    else
      @school_year = params[:school_year]
    end

    res_disciplinary_sanctions = Api::call "/students/#{@student.id}/disciplinary_sanctions/#{@school_year}"

    @school_years = res['school_years']
    @disciplinary_sanctions = res_disciplinary_sanctions['disciplinary_sanctions_for_year']
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_student
  before_action :set_person

  # GET /marks
  def index
    res = Api::call "/students/#{@student.id}/school_years"

    if params[:school_year].nil?
      @school_year = res['school_years'].last
      @school_year = @school_year['year'].to_s
    else
      @school_year = params[:school_year]
    end

    res_marks = Api::call "/students/#{@student.id}/marks/#{@school_year}"

    @school_years = res['school_years']
    @marks = res_marks['marks']
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student
  before_action :set_person

  # GET /welcome
  def index
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def chevron_icon
    '<i class="glyphicon glyphicon-chevron-left"></i>'.html_safe
  end
end

app/helpers/marks_helper.rb
module MarksHelper

	def format_mark_number(mark_row)
		"<strong> Nota #{mark_row['mark_number']}: </strong>"+"#{ mark_row['is_free'] == 0 ? format_mark(mark_row['mark']) : 'L'}&nbsp;"
	end

	def format_mark(mark)
		mark ? ("%.2f" % mark) : '-'
	end

	def format_examinations(examination, examination_instance)
		if examination_instance == "reg" && examination.first["examination_number"] == 1
			"#{ examination.first['is_absent'] == 0 ? format_mark(examination.first['mark']) : 'A'}"+" (#{ I18n.l examination.first['date'].to_date unless examination.first['date'].blank? })"
		else
			if examination.last["examination_number"] == 2
				"#{ examination.last['is_absent'] == 0 ? format_mark(examination.last['mark']) : 'A'}"
			else
				"-"
			end
		end
	end

	def format_repproveds(repproves)
		"#{ repproves.first['is_absent'] == 0 ? format_mark(repproves.first['mark']) : 'A'}"+" (#{ I18n.l repproves.first['date'].to_date unless repproves.first['date'] == nil })"
	end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/absences/index.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h2>Inasistencias <small> | <%= @person.firstname %> <%= @person.lastname %> - año lectivo <%= @school_year %></h1></small></h2>
  </div>

  <%= render partial: "shared/school_years_tabs", locals: { school_years: @school_years, school_year: @school_year } %>

  <%= form_tag(absences_path, method: "get", id: 'school_year_form') do %>
    <%= hidden_field_tag :school_year  %>
  <%-end-%>
  <div class="col-md-12 table-style">
    <div class="table-header">
      <h5><strong>Total de inasistencias: <%= @absences["total_absences"]%></strong></h5>
    </div>

    <% unless @absences["total_absences"].zero? %>
      <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="home">
           <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr class="info">
                  <th>Tipo</th>
                  <th>Cantidad</th>
                  <th>Fecha</th>
                </tr>
              </thead>
              <tbody>
                <% @absences['absences'].each do |absence|%>
                <tr>
                  <td><%= absence['absence_type'] %></td>
                  <td><%= absence['value'] %></td>
                  <td><%= I18n.l absence['day'].to_date %></td>
                </tr>
                <%end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<%= link_to(chevron_icon + 'Volver', root_path, class: 'btn btn-default btn-xs')%>
  </div>

<p style="margin: 45px;"></p>
</div>

app/views/application/_flashes.html.erb
<div class="flashes">
  <%- flash.each do |name, msg| %>
    <%= content_tag :div, class: "alert alert-#{ name == 'alert' ? 'danger' : 'success' } alert-dismissable" do -%>
      <div class="container">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg.html_safe %>
      </div>
    <% end -%>
  <% end -%>
</div>

app/views/application/_footer.html.erb
<footer class="footer footer-fixed-bottom">
  <div class="container">
    <p class="text-muted">Copyright © 2015 Facultad de Informática – UNLP. Todos los derechos reservados. 50 y 120 - La Plata, Argentina.</p>
  </div>
</footer>

app/views/application/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
    <a class="navbar-brand" href="<%= root_path %>"><%= image_tag("logo-kimkelen.png", alt: "Kimkëlen", class: 'logo') %></a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to('Inicio', root_path) %></li>
      <li><%= link_to('Calificaciones', marks_path) %></li>
      <li><%= link_to('Inasistencias', absences_path) %></li>
      <li><%= link_to('Sanciones disciplinarias', disciplinary_sanctions_path) %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <ul class="nav navbar-nav">
        <li class="mdi-content-mail" id="icon-envelope"></li>
      </ul>
      <li class="dropdown">
        <a href="#" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Hola, <%= @person.firstname %>! <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="javascript:void(0)">Mi perfil</a></li>
          <li class="divider"></li>
          <li><a href="javascript:void(0)">Cerrar sesión</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/application/forbidden.erb
<div class="container" style="margin-top: 20px">
  <div class="alert alert-error">
    <h4 class="alert-heading">
      <%=t 'views.errors.messages.forbidden' %>
    </h4>
    <%=t 'views.errors.messages.forbidden_message' %>
  </div>
</div>

app/views/application/not_found.erb
<div class="container" style="margin-top: 20px">
  <div class="alert alert-error">
    <h4 class="alert-heading">
      <%=t 'views.errors.messages.not_found' %>
    </h4>
    <%=t 'views.errors.messages.not_found_message' %>
  </div>
</div>

app/views/application/server_error.erb
<div class="container" style="margin-top: 20px">
  <div class="alert alert-error">
    <h4 class="alert-heading">
      <%=t 'views.errors.messages.something_went_wrong' %>
    </h4>
    <%=t 'views.errors.messages.something_went_wrong_messages' %>
  </div>
</div>

app/views/disciplinary_sanctions/index.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h2>Sanciones disciplinarias <small> | <%= @person.firstname %> <%= @person.lastname %> - año lectivo <%= @school_year %></h1></small></h2>
  </div>

  <%= render partial: "shared/school_years_tabs", locals: { school_years: @school_years, school_year: @school_year } %>

  <%= form_tag(disciplinary_sanctions_path, method: "get", id: 'school_year_form') do %>
    <%= hidden_field_tag :school_year  %>
  <%-end-%>
  <div class="col-md-12 table-style">
    <div class="table-header">
      <h5><strong>Total de sanciones: <%= @disciplinary_sanctions["total_disciplinary_sanctions"] %></strong></h5>
    </div>

    <% if @disciplinary_sanctions["total_disciplinary_sanctions"].zero? %>
     <p>No se registraron sanciones.</p>
    <% else %>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in" id="home">
         <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr class="info">
                <th>Fecha inicio</th>
                <th>Fecha fin</th>
                <th>Valor</th>
                <th>Número</th>
                <th>Tipo de sanción disciplinaria</th>
              </tr>
            </thead>
            <tbody>
              <% @disciplinary_sanctions['disciplinary_sanctions'].each do |disciplinary_sanction| %>
              <tr>
                <td><%= I18n.l disciplinary_sanction['request_date'].to_date unless disciplinary_sanction['request_date'].nil?%></td>
                <td><%= I18n.l disciplinary_sanction['resolution_date'].to_date unless disciplinary_sanction['resolution_date'].nil? %></td>
                <td><%= disciplinary_sanction['value'] %></td>
                <td><%= disciplinary_sanction['number'] %></td>
                <td><%= disciplinary_sanction['disciplinary_sanction_type'] %></td>
              </tr>
              <%end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
  </div>
<%= link_to(chevron_icon + 'Volver', root_path, class: 'btn btn-default btn-xs')%>
</div>


<p style="margin: 80px;"></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Kimkëlen - Acceso estudiantes</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="Students frontend">
  <meta name="author" content="Corrons María Emilia">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'navbar' %>
  <%= render 'flashes' %>
  <div class="container">
    <%= yield %>
  </div>
  <div id="footer">
    <%= render 'footer' %>
  </div>
</body>
</html>

app/views/marks/index.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h2>Calificaciones <small> | <%= @person.firstname %> <%= @person.lastname %> - año lectivo <%= @school_year %></h1></small></h2>
  </div>

  <%= form_tag(marks_path, method: "get", id: 'school_year_form') do %>
    <%= hidden_field_tag :school_year  %>
  <%-end-%>
  
  <%= render partial: "shared/school_years_tabs", locals: { school_years: @school_years, school_year: @school_year } %>
  <div class="col-md-12 table-style">

    <div class="table-header">
      <h4><span><strong><%= @marks['year']%>° año </strong></span><span style="padding-left: 8px"><strong>ESTADO: <%= @marks['status'] %></strong></span></h4>
    </div>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in" id="home">
         <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr class="info">
                <th>Materia</th>
                <th>Calificaciones</th>
                <th>Promedio cursada</th>
                <th>Ex. Regular</th>
                <th>Ex. Complementario</th>
                <th>Previas</th>
                <th>Promedio Def.</th>
              </tr>
            </thead>
            <tbody>
              <% @marks['course_subjects'].each do |course_subject|%>
              <tr>
                <td><%= course_subject['name'] %></td>
                 <td>
                  <% course_subject['marks'].each do |mark| %>
                   <%= format_mark_number(mark).html_safe %>
                  <%end%>
                </td>
                <td align="center"><%= format_mark(course_subject['average']) %></td>
                <td align="center"><%= course_subject['examinations'] == [] ? '-' : format_examinations(course_subject['examinations'], "reg") %></td>
                <td align="center"><%= course_subject['examinations'] == [] ? '-' : format_examinations(course_subject['examinations'], "comp") %></td>
                <td align="center"><%= course_subject['repproveds'] == [] ? '-' : format_repproveds(course_subject['repproveds']) %></td>
                <td align="center"><%= format_mark(course_subject['final_average']) unless course_subject['final_average'].nil? %></td>
              </tr>
              <%end %>
            </tbody>
            <tfoot>
            <td class='info average' colspan="7"> <strong>PROMEDIO ANUAL: <%= format_mark @marks['global_average'] %> </strong></td>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
<%= link_to(chevron_icon + 'Volver', root_path, class: 'btn btn-default btn-xs')%>
</div>

<p style="margin: 2em;"></p>

app/views/shared/_school_years_tabs.html.erb
<ul class="breadcrumb">
  <% @school_years.each do |school_year|%>
    <li class=<%=@school_year == school_year['year'].to_s ? "active-school-year" : "" %>>
      <a class="set-school-year" href="#" data-toggle="tab"><%= school_year['year']%></a>
    </li>
  <%-end-%>
</ul>

app/views/students/index.html.erb
<div class="col-md-12">
  <div class="row">
    <div class="tutor-container">
      <div class="col-md-6">
        <div class="tutor-view">
         <%= image_tag("student2.jpg", alt: "photo", class: 'photo') %>
        </div>
      </div>
      <div class="col-md-3 tutor-name">
        <div class="page-header">
          <h1><strong><%= @person.firstname%>, <%= @person.lastname %></strong></h1>
          <p class="identification-type"><strong>Legajo N° <%= @student.global_file_number %></strong></p>
        </div>
      </div>
      <legend></legend>
      <div class="col-md-3 children children1">
        <i class="mdi-action-grade"></i>
        <span>
          <h3><%= link_to('Calificaciones', marks_path) %></h3>
          <p class="list-group-item-text">Consultá tu historial académico <br> de calificaciones.</p>
          </span>
      </div>
      <div class="col-md-3 children children2">
        <i class="mdi-action-event"></i><span><h3><%= link_to('Inasistencias', absences_path) %></h3>
        <p class="list-group-item-text">Verificá tu registro de inasistencias 
        <br>y retrasos a clases.</p></span>
      </div>
      <div class="col-md-3 children children3">
        <i class="mdi-communication-live-help"></i><span><h3><%= link_to('Sanciones disciplinarias', disciplinary_sanctions_path) %></h3>
        <p class="list-group-item-text">Chequeá las sanciones disciplinarias <br> y apercibimientos.</p></span>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<p style="margin: 75px;"></p>

<div class="row">
  <div class="col-md-7">
     <div class="thumbnail">
      <div class="caption">
        <%= image_tag("student2.jpg", alt: "photo", class: 'photo') %>
        <div class="data">
          <h3 class="name"><%= @person['firstname'] %></h3>
          <span class="orientation">6°C Orientación Ciencias Naturales</span>
          <h1><i class="mdi-content-add-circle col-md-offset-10 icon-plus"></i></h1>
        </div>  

      </div>
    </div>
  </div>

  <div class="col-md-5 side-list">
    <div class="list-group">

      <div class="panel-default">
        <div class="panel-body home-boxes1">
          <div class="list-group-item clickable">
            <div class="row-action-primary">
              <i class="mdi-action-grade"></i>
            </div>
            <div class="row-content">
              <div class="action-secondary"><i class="mdi-material-info"></i></div>
              <p class="list-group-item-heading"><%= t('Marks') %></p>
              <h5><strong><i><%= link_to('Marks', marks_path) %></i></strong></h5>
              <p class="list-group-item-text">Mirá tu historial de calificaciones de cursadas y finales de materias.</p>
            </div>
          </div>
        </div>     
      </div>

      <div class="panel-default">
        <div class="panel-body home-boxes2">
          <div class="list-group-item clickable">
            <div class="row-action-primary">
              <i class="mdi-action-event"></i>
            </div>
            <div class="row-content">
              <div class="action-secondary"><i class="mdi-material-info"></i></div>
              <p class="list-group-item-heading">Inasistencias a clase</p>
              <h5><strong><i><%= link_to('Attendances', absences_path) %></i></strong></h5>
              <p class="list-group-item-text">Verificá tu registro de inasistencias y retrasos.</p>
            </div>
          </div>
        </div>
      </div>

      <div class="panel-default">
        <div class="panel-body home-boxes3">      
          <div class="list-group-item clickable">
            <div class="row-action-primary">
              <i class="mdi-notification-sim-card-alert"></i>
            </div>
            <div class="row-content">
              <div class="action-secondary"><i class="mdi-material-info"></i></div>
              <h4 class="list-group-item-heading">Sanciones disciplinarias</h4>
              <h5><strong><i><%= link_to('Disciplinary Sanctions', disciplinary_sanctions_path) %></i></strong></h5>
              <p class="list-group-item-text">Consultá las sanciones disciplinarias y apercibimientos que te han imputado.</p>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>